repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.1
    hooks:
      - id: ruff-check
        args: [--fix]
        files: ^((src/lies|tests|scripts)/|pyproject\.toml$)
      - id: ruff-format
        files: ^((src/lies|tests|scripts)/|pyproject\.toml$)
  - repo: local
    hooks:
      - id: typecheck
        name: make typecheck
        entry: uv run make typecheck
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: test
        name: make test
        entry: uv run make test
        language: system
        pass_filenames: false
        stages: [pre-commit]
