"""Pure TOML transform layer for providers.toml.

Re-validates after every mutation through the same rules as
``load_providers_config`` (``config.py:108-129``). No IO; the caller
commits the result via ``bootstrap.write_atomic``.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from lies.providers.agents import AGENT_ROSTER
from lies.providers.config import ProvidersConfig, ProviderSpec, parse_model_string
from lies.providers.errors import ProviderConfigError


@dataclass(frozen=True)
class ProvidersMutations:
    add_provider: ProviderSpec | None = None
    set_default: str | None = None
    set_agents: dict[str, str] = field(default_factory=dict)
    remove_agents: tuple[str, ...] = ()


def apply_mutations(cfg: ProvidersConfig, mut: ProvidersMutations) -> ProvidersConfig:
    """Return a new ``ProvidersConfig`` with mutations applied.

    Validates:
      - ``add_provider`` does not collide with an existing name.
      - ``set_default`` references a declared provider.
      - Each ``set_agents`` value references a declared provider.
      - No ``remove_agents`` name is an ``AGENT_ROSTER`` member, which
        the loader requires present in full.
    Re-validation re-uses ``parse_model_string`` from ``config.py`` so
    every write path produces a file ``load_providers_config`` would
    happily re-read.
    """
    providers = dict(cfg.providers)
    if mut.add_provider is not None:
        if mut.add_provider.name in providers:
            msg = (
                f"provider {mut.add_provider.name!r} already declared; "
                "edit it directly in providers.toml"
            )
            raise ProviderConfigError(msg)
        providers[mut.add_provider.name] = mut.add_provider

    default_model = cfg.default_model
    if mut.set_default is not None:
        provider_name, _ = parse_model_string(mut.set_default)
        if provider_name not in providers:
            msg = (
                f"set_default {mut.set_default!r} references undeclared "
                f"provider {provider_name!r}; declared providers: "
                f"{sorted(providers)}"
            )
            raise ProviderConfigError(msg)
        default_model = mut.set_default

    agents = dict(cfg.agents)
    for agent_name, raw in mut.set_agents.items():
        provider_name, _ = parse_model_string(raw)
        if provider_name not in providers:
            msg = (
                f"set_agents.{agent_name}={raw!r} references undeclared "
                f"provider {provider_name!r}; declared providers: "
                f"{sorted(providers)}"
            )
            raise ProviderConfigError(msg)
        agents[agent_name] = raw
    for agent_name in mut.remove_agents:
        if agent_name in AGENT_ROSTER:
            msg = (
                f"removing {agent_name!r} would leave the AGENT_ROSTER "
                "incomplete; the loader refuses incomplete rosters. Set "
                f"agents.{agent_name} to a different provider instead."
            )
            raise ProviderConfigError(msg)
        agents.pop(agent_name, None)

    return ProvidersConfig(
        providers=providers,
        default_model=default_model,
        agents=agents,
    )


def to_toml(cfg: ProvidersConfig) -> str:
    """Serialize ``ProvidersConfig`` to canonical TOML.

    Key order: ``default_model`` at the top (so it is a top-level key
    in TOML, not nested under the first ``[providers.<name>]`` table),
    then ``[providers.<name>]`` (alphabetical), then ``[agents]`` (in
    the order returned by ``dict`` iteration). One blank line between
    sections. Stable order keeps diffs readable.
    """
    lines: list[str] = []
    lines.append("# Generated by LIES providers bootstrap.")
    lines.append("# API key values are NOT stored here; only env var names.")
    lines.append("")
    lines.append(f'default_model = "{cfg.default_model}"')
    lines.append("")
    for name in sorted(cfg.providers):
        spec = cfg.providers[name]
        lines.append(f"[providers.{name}]")
        lines.append(f'type = "{spec.type}"')
        lines.append(f'api_key_env = "{spec.api_key_env}"')
        if spec.base_url is not None:
            lines.append(f'base_url = "{spec.base_url}"')
        lines.append("")
    lines.append("[agents]")
    for agent_name, raw in cfg.agents.items():
        lines.append(f'{agent_name} = "{raw}"')
    lines.append("")
    return "\n".join(lines)
